import numpy as np
import matplotlib.pyplot as plt 
# =========================================
def fact(x):
    if x == 0:
        return 1;
    return x*fact(x-1)

def f(x,n):
    return ((-1)**n)*(x**(2*n+1))/fact(2*n+1)
    
def sin(x):
    n = 10
    sine = 0
    for i in range(n):
        sine += f(x,i)
    return sine
    

x = np.linspace(-10,10,201)
# Store the sin(x) values generated by your function in the variable y
y = sin(x)
# Store the sin(x) values generated by using numpy in the variable x
yn = np.sin(x)

# Output
for i in range(len(x)):
    print("{:6.3f} {:6.3f}".format(x[i], y[i]))

# Plot
plt.plot(x,y, label = "my sine function")
plt.plot(x,yn, label = "numpy sine function")
plt.show()
